### ISSUE TITLE
Keep Alive Timer Only Runs Once

### ISSUE THREAD

**Issue by todddust** [ARMmbed/mbed-os-example-for-aws#24] opened 2020-09-29 23:26 UTC
I've modified this example to enable the keepAlive timer. I set the keepAlive to 30 
`connect_info.keepAliveSeconds = 30;`

I've also increased the publish period to 60 seconds:

`if (wait_sem.try_acquire_for(60000))`

With this setup a ping should be sent in between each publish to satisfy the KeepAlive timing. 

Watching on Wireshark I see the subscribe message go across. After that I don't see anything. Then 45 seconds later the server sends an Encryption Alert and closes the connection. 

The client in this case should have sent a PING to the server after 30 seconds of inactivity, but I never see it getting sent. 

Debugging the code a little I found that the KeepAlive Timer is implemented in the following file: mbed-aws-client\mbed\src\iot_clock.cpp.

I've put debug prints in thread_routine() and in IotClock_TimerArm. I've found the first time IotClock_TimerArm runs thread_routine() also runs and exits appropriately. However, the second call to IotClock_TimerArm doesn't cause thread_routine() to run, even though I can tell the code is getting to the thread.start call (via printfs).

Not sure what is going wrong here, any help is appreciated.

**Comment by ciarmcom** [comment] 2020-10-13 14:03
@todddust thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What target(s) are you using?
What toolchain(s) are you using?
What version of Mbed OS are you using (tag or sha)?
It would help if you could also specify the versions of any tools you are using?
How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'.This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirroredto our internal defect tracking system or investigated until this has been fully resolved.

**Comment by ciarmcom** [comment] 2020-10-18 13:45
@todddust it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by todddust** [comment] 2020-10-19 23:20
This is related to: https://github.com/ARMmbed/mbed-client-for-aws/issues/12. So if you use the latest code from that library the problem goes away. Thus I recommend updating the .lib file for that library.

**Comment by ciarmcom** [comment] 2020-10-23 13:46
@todddust it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-10-28 14:45
@todddust it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-04 18:04
@todddust it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-09 18:26
@todddust it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-14 21:35
@todddust it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-19 21:36
@todddust it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-25 06:39
@todddust it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by LDong-Arm** [comment] 2020-11-25 17:10
@todddust Thanks for looking into this issue. The library has already been updated so I'm closing this issue. Feel free to reopen it if the issue persists, thanks.

**Closed by LDong-Arm** 2020-11-25 17:10 UTC
