### ISSUE TITLE
AWS example are including some floating point symbols when build with  DISCO_L475VG_IOT01A

### ISSUE THREAD

**Issue by jamesbeyond** [ARMmbed/mbed-os-example-for-aws#12] opened 2020-07-13 14:51 UTC
When build this example on  DISCO_L475VG_IOT01A

run 
`python mbed-os/tools/test/examples/elf_float_checker.py mbed-os-example-aws.elf`
```
Checking ./mbed-os-example-aws/BUILD/DISCO_L475VG_IOT01A/GCC_ARM/mbed-os-example-aws.elf for floating point symbols
Failed - Found float symbols:
__aeabi_cdcmple
__aeabi_dcmpun
__aeabi_dcmpgt
__aeabi_cdcmpeq
__aeabi_dcmpeq
__aeabi_ui2d
__aeabi_dcmple
__aeabi_d2ulz
__aeabi_i2d
__aeabi_d2uiz
__aeabi_d2lz
__aeabi_dcmpge
__aeabi_d2f
__aeabi_l2d
__aeabi_dmul
__aeabi_dcmplt
__aeabi_f2d
__aeabi_ul2d
__aeabi_cdrcmple
__aeabi_ddiv
__aeabi_drsub
__aeabi_dadd
__aeabi_dsub
Found float symbols in ./mbed-os-example-aws/BUILD/DISCO_L475VG_IOT01A/GCC_ARM/mbed-os-example-aws.elf
```

**Comment by LDong-Arm** [comment] 2020-07-13 16:54
This happens when we enable the [wifi-ism43362](https://github.com/ARMmbed/wifi-ism43362) driver for DISCO_L475VG_IOT01A. It seems the driver itself doesn't use floating points, but its dependencies (some functions in the C library?) does.

**Comment by ciarmcom** [comment] 2020-10-13 14:03
@jamesbeyond thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What target(s) are you using?
What toolchain(s) are you using?
What version of Mbed OS are you using (tag or sha)?
It would help if you could also specify the versions of any tools you are using?
How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'.This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirroredto our internal defect tracking system or investigated until this has been fully resolved.

**Comment by ciarmcom** [comment] 2020-10-18 13:45
@jamesbeyond it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-10-23 13:46
@jamesbeyond it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-10-28 14:45
@jamesbeyond it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-04 18:04
@jamesbeyond it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-09 18:26
@jamesbeyond it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-14 21:35
@jamesbeyond it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-19 21:36
@jamesbeyond it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-11-25 06:39
@jamesbeyond it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by LDong-Arm** [comment] 2020-11-25 17:35
Created https://github.com/ARMmbed/wifi-ism43362/issues/87 for the WiFi driver. Closing this issue.

**Closed by LDong-Arm** 2020-11-25 17:35 UTC
