### ISSUE TITLE
Some symbols are missing when building with ARMC6

### ISSUE THREAD

**Issue by ithinuel** [ARMmbed/mbed-os-example-for-aws#6] opened 2020-06-06 21:12 UTC
1. `static_assert`
1. `open_memstream`
1. `IotClock_SleepMs`
1. `IotSemaphore_TryWait`
1. `IotMetrics_GetTcpConnections`

**Comment by 0xc0170** [comment] 2020-06-08 12:20
I assume this is related https://github.com/ARMmbed/mbed-os-example-aws/issues/3, so once this is fixed, both issues should be resolved

**Comment by LDong-Arm** [comment] 2020-06-11 14:35
This issue belongs to the https://github.com/ARMmbed/mbed-aws-client/ repository I believe

**Comment by ciarmcom** [comment] 2020-10-13 14:03
@ithinuel thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What target(s) are you using?
What toolchain(s) are you using?
What version of Mbed OS are you using (tag or sha)?
It would help if you could also specify the versions of any tools you are using?
How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'.This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirroredto our internal defect tracking system or investigated until this has been fully resolved.

**Comment by ciarmcom** [comment] 2020-10-18 13:45
@ithinuel it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment] 2020-10-23 13:46
@ithinuel it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by LDong-Arm** [comment] 2020-10-27 10:01
Compilation issues have been fixed long ago. As for any unimplemented features, they should belong to separate requests. I'm closing this, feel free to reopen if I missed something! @ithinuel

**Closed by LDong-Arm** 2020-10-27 10:01 UTC
